"""New migrate

Revision ID: 51ba7c9e1155
Revises: debace6e5504
Create Date: 2025-09-08 09:30:28.574668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ba7c9e1155'
down_revision = 'debace6e5504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoof_detection', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('spoof_detection')

    # ### end Alembic commands ###
