"""Add slots column to Class

Revision ID: 53c58f835d71
Revises: 51ba7c9e1155
Create Date: 2025-09-16 22:42:29.564954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c58f835d71'
down_revision = '51ba7c9e1155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('slots')

    # ### end Alembic commands ###
