"""Added validation fields to AttendanceRecord

Revision ID: 6202a27716f8
Revises: ac122675c6b1
Create Date: 2025-08-31 13:08:25.058514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6202a27716f8'
down_revision = 'ac122675c6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_valid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('geo_valid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('face_valid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_column('face_valid')
        batch_op.drop_column('geo_valid')
        batch_op.drop_column('qr_valid')

    # ### end Alembic commands ###
