"""Add AppConfig table for automatic_attendancell

Revision ID: 6372c77e3730
Revises: a40324e08b71
Create Date: 2025-09-18 23:05:40.587302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6372c77e3730'
down_revision = 'a40324e08b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_spoof_detection', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('auto_spoof_detection')

    # ### end Alembic commands ###
