"""Initial migration-3

Revision ID: 7b84554eddb5
Revises: abd28e13504c
Create Date: 2025-08-29 14:52:49.168685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b84554eddb5'
down_revision = 'abd28e13504c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('methods', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('qr_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('qr_rotate_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('geo_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('geo_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('geo_radius', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('attendance_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('attendance_student_id_fkey', 'student', ['student_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('geo_radius')
        batch_op.drop_column('geo_lng')
        batch_op.drop_column('geo_lat')
        batch_op.drop_column('qr_rotate_seconds')
        batch_op.drop_column('qr_type')
        batch_op.drop_column('methods')
        batch_op.drop_column('created_at')

    op.drop_table('attendance_record')
    # ### end Alembic commands ###
