"""Add AppConfig table for automatic_attendancell

Revision ID: a40324e08b71
Revises: 46ec5b2bc2e0
Create Date: 2025-09-18 22:51:42.746524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40324e08b71'
down_revision = '46ec5b2bc2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_attendance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_qr_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('auto_qr_rotate_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_geo_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_geo_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auto_geo_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auto_geo_radius', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_face_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('auto_face_enabled')
        batch_op.drop_column('auto_geo_radius')
        batch_op.drop_column('auto_geo_lng')
        batch_op.drop_column('auto_geo_lat')
        batch_op.drop_column('auto_geo_enabled')
        batch_op.drop_column('auto_qr_rotate_seconds')
        batch_op.drop_column('auto_qr_type')
        batch_op.drop_column('auto_attendance')

    # ### end Alembic commands ###
