"""Add branch, specialization, batch to student

Revision ID: abd28e13504c
Revises: a6b8b2385a07
Create Date: 2025-08-29 13:38:23.667407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd28e13504c'
down_revision = 'a6b8b2385a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('batch', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('batch')
        batch_op.drop_column('specialization')
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
