"""Initial migration-4

Revision ID: ac122675c6b1
Revises: af7684ea80c6
Create Date: 2025-08-29 15:45:07.601515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac122675c6b1'
down_revision = 'af7684ea80c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_generated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('current_qr',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('current_qr',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('qr_generated_at')

    # ### end Alembic commands ###
