"""Initial migration-7

Revision ID: af7684ea80c6
Revises: 7b84554eddb5
Create Date: 2025-08-29 15:42:41.937067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7684ea80c6'
down_revision = '7b84554eddb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_qr', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('current_qr')

    # ### end Alembic commands ###
