"""empty message

Revision ID: c8cfbebc4543
Revises: 1501947c0d18
Create Date: 2025-09-23 23:33:59.262505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cfbebc4543'
down_revision = '1501947c0d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('close_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('close_at')
        batch_op.drop_column('open_at')

    # ### end Alembic commands ###
