"""empty message

Revision ID: debace6e5504
Revises: 4df542f82556
Create Date: 2025-09-06 23:54:59.917358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debace6e5504'
down_revision = '4df542f82556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('co_curricular', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('internships', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('internships')
        batch_op.drop_column('co_curricular')
        batch_op.drop_column('academics')

    # ### end Alembic commands ###
